name: "Echo bot v2"
on:
  issue_comment:
    types: [created]
jobs:
 ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Chat
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          issue-type: issue
          commands: |
            ping
