name: "Echo bot v2"
on:
  issue_comment:
    types: [created]
jobs:
 ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        token: ${{ secrets.PAT }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Chat
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          permission: none
          issue-type: issue
          commands: |
            ping
